FROM oven/bun:latest

WORKDIR /user/src/app

ARG DATABASE_URL

COPY ./packages ./packages
COPY ./bun.lock ./bun.lock

COPY ./package-lock.json ./package-lock.json
COPY ./turbo.json ./turbo.json
COPY ./apps/web ./apps/web


COPY . .

RUN bun install
RUN bun run db:generate 
RUN DATABASE_URL=${DATABASE_URL} bun run build

EXPOSE 4000

CMD ["bun", "run", "start:frontend"]