FROM oven/bun:latest

WORKDIR /user/src/app

COPY ./packages ./packages
COPY ./bun.lock ./bun.lock

COPY ./package-lock.json ./package-lock.json
COPY ./turbo.json ./turbo.json
COPY ./apps/backend ./apps/backend


COPY . .

RUN bun install
RUN bun run db:generate 

EXPOSE 8080

CMD ["bun", "run", "start:backend"]