name: Deploy Backend

on:
  push:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.backend
          push: true
          tags: sathwik09/deploy-mono-cicd-backend:latest

      - name: Deploy to VM
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/ssh_key
          chmod 600 ~/ssh_key
          ssh -o StrictHostKeyChecking=no -i ~/ssh_key ubuntu@3.110.175.103 -t "
            docker stop user_backend || true
            docker rm user_backend || true
            docker pull sathwik09/deploy-mono-cicd-backend:latest
            docker run --name user_backend -d -p 8080:8080 sathwik09/deploy-mono-cicd-backend:latest
          "
